files = ['.']

fs = require 'fs'
{print} = require 'util'
{spawn, exec} = require 'child_process'

# ANSI Terminal Colors
bold = '\x1b[0;1m'
green = '\x1b[0;32m'
reset = '\x1b[0m'
red = '\x1b[0;31m'

# add watch task
task 'watch', 'compile and watch', -> build true, -> log ":-)", green

# log some intersting messages to the console
log = (message, color, explanation) ->
        console.log color + message + reset + ' ' + (explanation or '')

# make node run a command
launch = (cmd, options=[], callback) ->
  app = spawn cmd, options
  app.stdout.pipe(process.stdout)
  app.stderr.pipe(process.stderr)
  app.on 'exit', (status) -> callback?() if status is 0

# the build task that builds/watches my projects for changes
build = (watch, callback) ->
  options = ['-c', '-b', '.']
  options.concat files
  options.unshift '-w' if watch
  launch 'coffee', options, callback
